cup_cakes_homepage:
    path:     /Patisserie
    defaults: { _controller: CupCakesBundle:Default:index }
cup_cakes_Dashbord:
    path:    /Admin
    defaults: { _controller: CupCakesBundle:Default:Admin }
cup_cakes_Eshop:
    path:   /Client
    defaults: { _controller: CupCakesBundle:Default:client }
cup_cakes_Formateur:
    path:   /Formateur
    defaults: { _controller: CupCakesBundle:Default:Formateur }
