<?php

namespace CupCakesBundle\Repository;

/**
 * educateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class educateRepository extends \Doctrine\ORM\EntityRepository
{
}
