<?php

namespace CupCakesBundle\Repository;

/**
 * LinePromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinePromoRepository extends \Doctrine\ORM\EntityRepository
{
}
