<?php

namespace CupCakesBundle\Repository;

/**
 * LineCmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineCmdRepository extends \Doctrine\ORM\EntityRepository
{
}
